spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zyh282194718
    url: jdbc:mysql://193.112.97.27/mydb?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
  jpa:
    show-sql: true
server:
  port: 80